.TH "Aircraft" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aircraft
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Aircraft\&.hpp>\fP
.PP
Inherits \fBEntity\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBEagle\fP, \fBRaptor\fP }"
.br
.in -1c

Public Types inherited from \fBSceneNode\fP
.in +1c
.ti -1c
.RI "typedef std::unique_ptr< \fBSceneNode\fP > \fBPtr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAircraft\fP (\fBType\fP type, \fBGame\fP *\fBgame\fP)"
.br
.in -1c

Public Member Functions inherited from \fBEntity\fP
.in +1c
.ti -1c
.RI "\fBEntity\fP (\fBGame\fP *\fBgame\fP)"
.br
.ti -1c
.RI "void \fBsetVelocity\fP (XMFLOAT2 velocity)"
.br
.ti -1c
.RI "void \fBsetVelocity\fP (float vx, float vy)"
.br
.ti -1c
.RI "XMFLOAT2 \fBgetVelocity\fP () const"
.br
.ti -1c
.RI "virtual void \fBupdateCurrent\fP (const GameTimer &gt)"
.br
.in -1c

Public Member Functions inherited from \fBSceneNode\fP
.in +1c
.ti -1c
.RI "\fBSceneNode\fP (\fBGame\fP *\fBgame\fP)"
.br
.ti -1c
.RI "void \fBattachChild\fP (\fBPtr\fP child)"
.br
.ti -1c
.RI "\fBPtr\fP \fBdetachChild\fP (const \fBSceneNode\fP &node)"
.br
.ti -1c
.RI "void \fBupdate\fP (const GameTimer &gt)"
.br
.ti -1c
.RI "void \fBdraw\fP () const"
.br
.ti -1c
.RI "void \fBbuild\fP ()"
.br
.ti -1c
.RI "XMFLOAT3 \fBgetWorldPosition\fP () const"
.br
.ti -1c
.RI "void \fBsetPosition\fP (float x, float y, float z)"
.br
.ti -1c
.RI "XMFLOAT3 \fBgetWorldRotation\fP () const"
.br
.ti -1c
.RI "void \fBsetWorldRotation\fP (float x, float y, float z)"
.br
.ti -1c
.RI "XMFLOAT3 \fBgetWorldScale\fP () const"
.br
.ti -1c
.RI "void \fBsetScale\fP (float x, float y, float z)"
.br
.ti -1c
.RI "XMFLOAT4X4 \fBgetWorldTransform\fP () const"
.br
.ti -1c
.RI "XMFLOAT4X4 \fBgetTransform\fP () const"
.br
.ti -1c
.RI "void \fBmove\fP (float x, float y, float z)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBEntity\fP
.in +1c
.ti -1c
.RI "XMFLOAT2 \fBmVelocity\fP"
.br
.in -1c

Protected Attributes inherited from \fBSceneNode\fP
.in +1c
.ti -1c
.RI "\fBGame\fP * \fBgame\fP"
.br
.ti -1c
.RI "\fBRenderItem\fP * \fBrenderer\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBAircraft::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEagle \fP\fP
.TP
\fB\fIRaptor \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Aircraft::Aircraft (\fBType\fP type, \fBGame\fP * game)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Game3015-A1 from the source code\&.
