.TH "Starter Directory Reference" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Starter Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAircraft\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAircraft\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEntity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEntity\&.hpp\fP"
.br
.ti -1c
.RI "file \fBFrameResource\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFrameResource\&.h\fP"
.br
.ti -1c
.RI "file \fBGame\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGame\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSceneNode\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSceneNode\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSpriteNode\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSpriteNode\&.h\fP"
.br
.ti -1c
.RI "file \fBWorld\&.cpp\fP"
.br
.ti -1c
.RI "file \fBWorld\&.hpp\fP"
.br
.in -1c
