.TH "Starter/FrameResource.h" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Starter/FrameResource.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Common/d3dUtil\&.h'\fP
.br
\fC#include '\&.\&./Common/MathHelper\&.h'\fP
.br
\fC#include '\&.\&./Common/UploadBuffer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBObjectConstants\fP"
.br
.ti -1c
.RI "struct \fBPassConstants\fP"
.br
.ti -1c
.RI "struct \fBVertex\fP"
.br
.ti -1c
.RI "struct \fBFrameResource\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game3015-A1 from the source code\&.
