.TH "Starter/Game.cpp" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Starter/Game.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Game\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBgNumFrameResources\fP = 3"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int gNumFrameResources = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for Game3015-A1 from the source code\&.
