.TH "Starter/main.cpp" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Starter/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Game\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int WINAPI \fBWinMain\fP (HINSTANCE hInstance, HINSTANCE prevInstance, PSTR cmdLine, int showCmd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE prevInstance, PSTR cmdLine, int showCmd)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Game3015-A1 from the source code\&.
