.TH "ObjectConstants" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectConstants
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FrameResource\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DirectX::XMFLOAT4X4 \fBWorld\fP = MathHelper::Identity4x4()"
.br
.ti -1c
.RI "DirectX::XMFLOAT4X4 \fBTexTransform\fP = MathHelper::Identity4x4()"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "DirectX::XMFLOAT4X4 ObjectConstants::TexTransform = MathHelper::Identity4x4()"

.SS "DirectX::XMFLOAT4X4 ObjectConstants::World = MathHelper::Identity4x4()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Game3015-A1 from the source code\&.
