.TH "Starter/SpriteNode.h" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Starter/SpriteNode.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Entity\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpriteNode\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game3015-A1 from the source code\&.
