.TH "Vertex" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FrameResource\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DirectX::XMFLOAT3 \fBPos\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT3 \fBNormal\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT2 \fBTexC\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "DirectX::XMFLOAT3 Vertex::Normal"

.SS "DirectX::XMFLOAT3 Vertex::Pos"

.SS "DirectX::XMFLOAT2 Vertex::TexC"


.SH "Author"
.PP 
Generated automatically by Doxygen for Game3015-A1 from the source code\&.
