.TH "World" 3 "Wed Feb 1 2023" "Game3015-A1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
World
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <World\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorld\fP (\fBGame\fP *window)"
.br
.ti -1c
.RI "void \fBupdate\fP (const GameTimer &gt)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBbuildScene\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "World::World (\fBGame\fP * window)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void World::buildScene ()"

.SS "void World::draw ()"

.SS "void World::update (const GameTimer & gt)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Game3015-A1 from the source code\&.
